# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: host
    displayName: HOST
    type: string
    default: NULL
    values:
      - NULL
      - tit.kosik.osdc1.mall.local
      - bobek.kosik.osdc1.mall.local
      - brada.kosik.osdc1.mall.local
      - cecek.kosik.osdc1.mall.local
      - kopyto.kosik.osdc1.mall.local
      - trkal.kosik.osdc1.mall.local
      - fousek.kosik.osdc1.mall.local
      - mobile.kosik.osdc1.mall.local
      - mobile-integration.kosik.osdc2.mall.local
      - zvejkal.kosik.osdc2.mall.local
      - veminko.kosik.osdc2.mall.local
      - lizinka.kosik.osdc2.mall.local
      - epc-dev-integration.kosik.osdc2.mall.local
      - roza.kosik.osdc2.mall.local
      - pepina.kosik.osdc2.mall.local
      - lizinka.kosik.os.mall.local

  - name: version
    displayName: Version
    default: origin/master

  - name: domain
    displayName: K3W_domain
    default: cz
    values:
      - cz
      - bg

trigger: none


pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
