# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: host
    displayName: HOST
    type: string
    default: lizinka
    values:
      - lizinka
      - brada
      - kopyto

  - name: version
    displayName: Version
    default: origin/master

  - name: domain
    displayName: K3W_domain
    default: cz
    values:
      - cz
      - bg
      

trigger: none


pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
