name: Test nightly
on:
  schedule:
    - cron: '0/6 * * * *'
    - cron: '3/6 * * * *'

jobs:

  test:
    runs-on:
      - ubuntu-latest
    steps:
      - name: setenv
        if: github.event.schedule=='0/6 * * * *'
        run: |
          echo "::set-env name=cronenv::even"
      - name: setenv2
        if: github.event.schedule=='3/6 * * * *'
        run: |
          echo "::set-env name=cronenv::odd"
      - name: check env value
        run: |
          echo $cronenv  
