name: Test nightly
on:
  push:
  schedule:
    - cron: '0/10 * * * *'
    - cron: '5/10 * * * *'

jobs:

  test:
    runs-on:
      - ubuntu-latest
    steps:
      - name: setenv
        if: github.event.schedule=='0/10 * * * *'
        run: |
          echo "CRON=even" >> $GITHUB_ENV
          
      - name: setenv2
        if: github.event.schedule=='5/10 * * * *'
        run: |
          echo "CRON=odd" >> $GITHUB_ENV
          
      - name: check env value
        run: |
          echo ${{ env.CRON }} 
