name: main-workflow
on: push

jobs:
  test:
    uses: garnetstar/pipeline-k3w/.github/workflows/test.yml@a363e1d974035c67c3bae86b8f996341929958cd
  build:
    needs: [test]
    uses: garnetstar/pipeline-k3w/.github/workflows/build.yml@a363e1d974035c67c3bae86b8f996341929958cd
  preprod:
    name: deploy to preprod
    needs: [ build ]
    uses: garnetstar/pipeline-k3w/.github/workflows/deploy-preprod.yml@a363e1d974035c67c3bae86b8f996341929958cd